### ISSUE TITLE
Question - Purpose of the "test" dashboard subdomain

### ISSUE THREAD

**Issue by daigo75** [Freemius/freemius-users-dashboard#6]
The plugin code contains the following:
~~~
if ( ! defined( 'WP_FS__MEMBERS_DASHBOARD_SUBDOMAIN' ) ) {
    define( 'WP_FS__MEMBERS_DASHBOARD_SUBDOMAIN', WP_FS__MEMBERS_DASHBOARD_DEBUG ?
        'http://users.freemius-local.com:4200/dashboard.js' :
        'https://users.freemius.com/dashboard.js'
   );
}
~~~

The purpose is to switch the URL to the dashboard script to `http://users.freemius-local.com:4200/dashboard.js` when the debug mode is enabled. I noticed that `users.freemius-local.com` is not a real domain, so I suppose that it should be some sort of test domain (or a local one). Still, I can't fully figure out why one should use it. Is there any specific scenario where one could need to host a local copy of the dashboard script?

**Comment by vovafeldman** [comment]
@daigo75 this is for our own local testing, there's no reason for you to use it. In theory, you're right, potentially you can host the script on your end. We haven't tested it, so I don't know if it will work smoothly.

**Comment by daigo75** [comment]
Thanks for the clarification. Since I'm implementing a similar logic, but independently, I will skip that part. 👍
